-- Mutha Quality Portal: Registration + Plant/Department Masters + Complete Admin History + Notification Queue
-- Run AFTER PORTAL_ACCESS_MASTERPART_AUDIT.sql and SCANNING_DWM_OEE_UPGRADE.sql

-- 1) Registration master lists
CREATE TABLE IF NOT EXISTS public.portal_plants (
 id bigint generated by default as identity primary key,
 plant_code text unique not null,
 plant_name text unique not null,
 active boolean not null default true,
 created_at timestamptz default now()
);

CREATE TABLE IF NOT EXISTS public.portal_departments (
 id bigint generated by default as identity primary key,
 department_name text unique not null,
 active boolean not null default true,
 created_at timestamptz default now()
);

INSERT INTO public.portal_plants(plant_code,plant_name) VALUES
 ('MFPL','MFPL'),('MEPL-U3','MEPL-U3'),('MEPL-H21','MEPL-H21'),('MEPL-H25','MEPL-H25'),('DI','DI'),('MSL','MSL')
ON CONFLICT (plant_name) DO NOTHING;

INSERT INTO public.portal_departments(department_name) VALUES
 ('Quality Assurance'),('Development'),('Production'),('Maintenance'),('Tool Room'),('Stores'),('Purchase'),('PPC'),('Engineering'),('Foundry'),('Machining'),('Dispatch / Logistics'),('HR / Admin'),('IT'),('Finance / Accounts'),('EHS / Safety'),('Sales / Marketing'),('Other')
ON CONFLICT (department_name) DO NOTHING;

ALTER TABLE public.portal_plants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.portal_departments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public can view active portal plants" ON public.portal_plants;
DROP POLICY IF EXISTS "Public can view active portal departments" ON public.portal_departments;
DROP POLICY IF EXISTS "Admins manage portal plants" ON public.portal_plants;
DROP POLICY IF EXISTS "Admins manage portal departments" ON public.portal_departments;
CREATE POLICY "Public can view active portal plants" ON public.portal_plants FOR SELECT TO anon, authenticated USING (active=true);
CREATE POLICY "Public can view active portal departments" ON public.portal_departments FOR SELECT TO anon, authenticated USING (active=true);
CREATE POLICY "Admins manage portal plants" ON public.portal_plants FOR ALL TO authenticated USING (public.is_portal_admin()) WITH CHECK (public.is_portal_admin());
CREATE POLICY "Admins manage portal departments" ON public.portal_departments FOR ALL TO authenticated USING (public.is_portal_admin()) WITH CHECK (public.is_portal_admin());

-- 2) Registration notification preferences
ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS whatsapp_opt_in boolean not null default true;
ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS email_opt_in boolean not null default true;
ALTER TABLE public.user_profiles ADD COLUMN IF NOT EXISTS last_profile_update_at timestamptz;

-- 3) Complete admin/user activity history
CREATE TABLE IF NOT EXISTS public.portal_admin_history (
 id bigint generated by default as identity primary key,
 entity_type text not null,
 entity_id text,
 action text not null,
 target_user_id uuid references auth.users(id) on delete set null,
 actor_id uuid references auth.users(id) on delete set null,
 actor_name text,
 actor_email text,
 actor_mobile text,
 description text,
 old_data jsonb,
 new_data jsonb,
 created_at timestamptz default now()
);
CREATE INDEX IF NOT EXISTS idx_admin_history_created ON public.portal_admin_history(created_at desc);
CREATE INDEX IF NOT EXISTS idx_admin_history_target ON public.portal_admin_history(target_user_id);
ALTER TABLE public.portal_admin_history ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admins view admin history" ON public.portal_admin_history;
CREATE POLICY "Admins view admin history" ON public.portal_admin_history FOR SELECT TO authenticated USING (public.is_portal_admin());

-- 4) Notification queue for Email and WhatsApp
CREATE TABLE IF NOT EXISTS public.portal_notifications (
 id bigint generated by default as identity primary key,
 event_type text not null,
 module text,
 record_id text,
 recipient_user_id uuid references auth.users(id) on delete set null,
 recipient_name text,
 recipient_email text,
 recipient_mobile text,
 channel text not null check (channel in ('EMAIL','WHATSAPP')),
 subject text,
 message text not null,
 status text not null default 'Pending' check (status in ('Pending','Processing','Sent','Failed','Skipped')),
 provider_message_id text,
 error_message text,
 created_at timestamptz default now(),
 sent_at timestamptz
);
CREATE INDEX IF NOT EXISTS idx_notifications_status ON public.portal_notifications(status,created_at);
ALTER TABLE public.portal_notifications ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admins view notifications" ON public.portal_notifications;
DROP POLICY IF EXISTS "Users view own notifications" ON public.portal_notifications;
CREATE POLICY "Admins view notifications" ON public.portal_notifications FOR SELECT TO authenticated USING (public.is_portal_admin());
CREATE POLICY "Users view own notifications" ON public.portal_notifications FOR SELECT TO authenticated USING (recipient_user_id=auth.uid());

-- 5) Helper: profile contact data
CREATE OR REPLACE FUNCTION public.portal_profile(p_user uuid)
RETURNS TABLE(employee_name text, official_email text, mobile_no text, whatsapp_opt_in boolean, email_opt_in boolean)
LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$
 SELECT employee_name,official_email,mobile_no,coalesce(whatsapp_opt_in,true),coalesce(email_opt_in,true)
 FROM public.user_profiles WHERE id=p_user;
$$;

-- 6) Admin history trigger for user profile changes
CREATE OR REPLACE FUNCTION public.log_user_profile_change()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE a public.user_profiles%ROWTYPE; target_name text; target_email text; target_mobile text;
BEGIN
 SELECT * INTO a FROM public.user_profiles WHERE id=auth.uid();
 target_name:=coalesce(NEW.employee_name,OLD.employee_name);
 target_email:=coalesce(NEW.official_email,OLD.official_email);
 target_mobile:=coalesce(NEW.mobile_no,OLD.mobile_no);
 INSERT INTO public.portal_admin_history(entity_type,entity_id,action,target_user_id,actor_id,actor_name,actor_email,actor_mobile,description,old_data,new_data)
 VALUES('user_profile',coalesce(NEW.id,OLD.id)::text,TG_OP,coalesce(NEW.id,OLD.id),auth.uid(),a.employee_name,a.official_email,a.mobile_no,
 'User profile / registration details updated',CASE WHEN TG_OP IN ('UPDATE','DELETE') THEN to_jsonb(OLD) END,CASE WHEN TG_OP IN ('INSERT','UPDATE') THEN to_jsonb(NEW) END);
 RETURN coalesce(NEW,OLD);
END; $$;
DROP TRIGGER IF EXISTS trg_admin_history_user_profile ON public.user_profiles;
CREATE TRIGGER trg_admin_history_user_profile AFTER INSERT OR UPDATE OR DELETE ON public.user_profiles FOR EACH ROW EXECUTE FUNCTION public.log_user_profile_change();

-- 7) Admin history trigger for permissions
CREATE OR REPLACE FUNCTION public.log_permission_change()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE a public.user_profiles%ROWTYPE; t uuid;
BEGIN
 t:=coalesce(NEW.user_id,OLD.user_id);
 SELECT * INTO a FROM public.user_profiles WHERE id=auth.uid();
 INSERT INTO public.portal_admin_history(entity_type,entity_id,action,target_user_id,actor_id,actor_name,actor_email,actor_mobile,description,old_data,new_data)
 VALUES('user_permission',coalesce(NEW.id,OLD.id)::text,TG_OP,t,auth.uid(),a.employee_name,a.official_email,a.mobile_no,
 'Module View/Add/Edit permission updated',CASE WHEN TG_OP IN ('UPDATE','DELETE') THEN to_jsonb(OLD) END,CASE WHEN TG_OP IN ('INSERT','UPDATE') THEN to_jsonb(NEW) END);
 RETURN coalesce(NEW,OLD);
END; $$;
DROP TRIGGER IF EXISTS trg_admin_history_permission ON public.user_module_permissions;
CREATE TRIGGER trg_admin_history_permission AFTER INSERT OR UPDATE OR DELETE ON public.user_module_permissions FOR EACH ROW EXECUTE FUNCTION public.log_permission_change();

-- 8) Extend existing portal audit to scanning tasks
DROP TRIGGER IF EXISTS trg_audit_scanning_tasks ON public.scanning_tasks;
CREATE TRIGGER trg_audit_scanning_tasks AFTER INSERT OR UPDATE OR DELETE ON public.scanning_tasks FOR EACH ROW EXECUTE FUNCTION public.log_portal_change('scanning_dwm');

-- 9) Notification helper: notify target user when profile changes
CREATE OR REPLACE FUNCTION public.queue_profile_notifications()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE msg text; subj text; nm text; em text; mob text; w boolean; e boolean;
BEGIN
 IF TG_OP='UPDATE' THEN
   IF coalesce(NEW.employee_name,'')=coalesce(OLD.employee_name,'') AND
      coalesce(NEW.department,'')=coalesce(OLD.department,'') AND
      coalesce(NEW.designation,'')=coalesce(OLD.designation,'') AND
      coalesce(NEW.plant_unit,'')=coalesce(OLD.plant_unit,'') AND
      coalesce(NEW.role,'')=coalesce(OLD.role,'') AND
      coalesce(NEW.approval_status,'')=coalesce(OLD.approval_status,'') THEN
      RETURN NEW;
   END IF;
 END IF;
 nm:=NEW.employee_name; em:=NEW.official_email; mob:=NEW.mobile_no; w:=coalesce(NEW.whatsapp_opt_in,true); e:=coalesce(NEW.email_opt_in,true);
 subj:='Mutha Quality Portal - Profile/Access Update';
 msg:='Your Mutha Quality Portal profile/access has been updated. Plant: '||coalesce(NEW.plant_unit,'-')||', Department: '||coalesce(NEW.department,'-')||', Role: '||coalesce(NEW.role,'-')||', Status: '||coalesce(NEW.approval_status,'-')||'.';
 IF e AND em IS NOT NULL AND em<>'' THEN INSERT INTO public.portal_notifications(event_type,module,record_id,recipient_user_id,recipient_name,recipient_email,recipient_mobile,channel,subject,message) VALUES('USER_PROFILE_UPDATE','user_profile',NEW.id::text,NEW.id,nm,em,mob,'EMAIL',subj,msg); END IF;
 IF w AND mob IS NOT NULL AND mob<>'' THEN INSERT INTO public.portal_notifications(event_type,module,record_id,recipient_user_id,recipient_name,recipient_email,recipient_mobile,channel,subject,message) VALUES('USER_PROFILE_UPDATE','user_profile',NEW.id::text,NEW.id,nm,em,mob,'WHATSAPP',subj,msg); END IF;
 NEW.last_profile_update_at:=now();
 RETURN NEW;
END; $$;
DROP TRIGGER IF EXISTS trg_queue_profile_notifications ON public.user_profiles;
CREATE TRIGGER trg_queue_profile_notifications BEFORE UPDATE ON public.user_profiles FOR EACH ROW EXECUTE FUNCTION public.queue_profile_notifications();

-- 10) Notify assigned scanning engineer when a task is assigned/updated
CREATE OR REPLACE FUNCTION public.queue_scanning_notifications()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE p public.user_profiles%ROWTYPE; msg text; subj text; nm text; em text; mob text; w boolean; e boolean;
BEGIN
 IF NEW.assigned_engineer_id IS NULL THEN RETURN NEW; END IF;
 SELECT up.* INTO p FROM public.user_profiles up JOIN public.scanning_engineers se ON se.user_id=up.id WHERE se.id=NEW.assigned_engineer_id;
 IF p.id IS NULL THEN RETURN NEW; END IF;
 IF TG_OP='UPDATE' AND NEW.work_status=OLD.work_status AND NEW.assigned_engineer_id=OLD.assigned_engineer_id AND NEW.task_date=OLD.task_date AND NEW.priority=OLD.priority THEN RETURN NEW; END IF;
 nm:=p.employee_name; em:=p.official_email; mob:=p.mobile_no; w:=coalesce(p.whatsapp_opt_in,true); e:=coalesce(p.email_opt_in,true);
 subj:='Mutha Quality Portal - Scanning Task Update';
 msg:='3D Scanning task update: Date '||coalesce(NEW.task_date::text,'-')||', Shift '||coalesce(NEW.shift_code,'-')||', Plant '||coalesce(NEW.plant_unit,'-')||', Customer '||coalesce(NEW.customer_name,'-')||', Part '||coalesce(NEW.part_short_name,'-')||', Priority '||coalesce(NEW.priority,'-')||', Status '||coalesce(NEW.work_status,'-')||'.';
 IF e AND em IS NOT NULL AND em<>'' THEN INSERT INTO public.portal_notifications(event_type,module,record_id,recipient_user_id,recipient_name,recipient_email,recipient_mobile,channel,subject,message) VALUES('SCANNING_TASK_UPDATE','scanning_dwm',NEW.id::text,p.id,nm,em,mob,'EMAIL',subj,msg); END IF;
 IF w AND mob IS NOT NULL AND mob<>'' THEN INSERT INTO public.portal_notifications(event_type,module,record_id,recipient_user_id,recipient_name,recipient_email,recipient_mobile,channel,subject,message) VALUES('SCANNING_TASK_UPDATE','scanning_dwm',NEW.id::text,p.id,nm,em,mob,'WHATSAPP',subj,msg); END IF;
 RETURN NEW;
END; $$;
DROP TRIGGER IF EXISTS trg_queue_scanning_notifications ON public.scanning_tasks;
CREATE TRIGGER trg_queue_scanning_notifications AFTER INSERT OR UPDATE ON public.scanning_tasks FOR EACH ROW EXECUTE FUNCTION public.queue_scanning_notifications();

-- 11) Admin can see/update notification status; users only see their own
DROP POLICY IF EXISTS "Admins manage notifications" ON public.portal_notifications;
CREATE POLICY "Admins manage notifications" ON public.portal_notifications FOR ALL TO authenticated USING (public.is_portal_admin()) WITH CHECK (public.is_portal_admin());

-- 12) Helpful indexes
CREATE INDEX IF NOT EXISTS idx_profiles_plant_department ON public.user_profiles(plant_unit,department);
