-- Mutha Quality Portal: Access Control + WLS + Plant-wise Master Part List + Audit Log
-- Run ONCE in Supabase SQL Editor. Existing Engineering Drawing records are preserved.

create table if not exists public.user_module_permissions (
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 module text not null check (module in ('engineering_drawing','wls','master_part')),
 can_view boolean not null default false,
 can_add boolean not null default false,
 can_edit boolean not null default false,
 updated_at timestamptz not null default now(),
 unique(user_id,module)
);

create table if not exists public.master_part_list (
 id bigint generated by default as identity primary key,
 plant_unit text not null,
 customer_name text,
 part_no text not null,
 part_name text not null,
 drawing_no text,
 revision text,
 part_type text,
 material text,
 process text,
 model text,
 status text default 'Active',
 remarks text,
 created_by uuid references auth.users(id),
 updated_by uuid references auth.users(id),
 created_at timestamptz default now(),
 updated_at timestamptz default now()
);

create table if not exists public.portal_audit_log (
 id bigint generated by default as identity primary key,
 module text not null,
 record_id text not null,
 action text not null check (action in ('INSERT','UPDATE','DELETE')),
 actor_id uuid references auth.users(id),
 actor_name text,
 actor_mobile text,
 actor_email text,
 record_label text,
 old_data jsonb,
 new_data jsonb,
 created_at timestamptz default now()
);

create table if not exists public.whatsapp_notifications (
 id bigint generated by default as identity primary key,
 audit_id bigint references public.portal_audit_log(id) on delete cascade,
 recipient_user_id uuid references auth.users(id) on delete set null,
 recipient_name text,
 recipient_mobile text,
 message text not null,
 status text default 'Pending',
 sent_at timestamptz,
 created_at timestamptz default now()
);

create or replace function public.is_portal_admin()
returns boolean language sql security definer set search_path=public as $$
 select exists(select 1 from public.user_profiles
 where id=auth.uid() and approval_status='Approved' and role='Admin');
$$;

create or replace function public.has_module_access(p_module text,p_action text)
returns boolean language plpgsql security definer set search_path=public as $$
declare ok boolean;
begin
 if public.is_portal_admin() then return true; end if;
 select case p_action when 'view' then can_view when 'add' then can_add when 'edit' then can_edit else false end
 into ok from public.user_module_permissions
 where user_id=auth.uid() and module=p_module;
 return coalesce(ok,false);
end; $$;

-- Engineering Drawing RLS
alter table public.engineering_drawing_register enable row level security;
drop policy if exists "Authenticated users can view drawing register" on public.engineering_drawing_register;
drop policy if exists "Authenticated users can add drawing register" on public.engineering_drawing_register;
drop policy if exists "Authenticated users can update drawing register" on public.engineering_drawing_register;
drop policy if exists "Portal users can view drawing register" on public.engineering_drawing_register;
drop policy if exists "Portal users can add drawing register" on public.engineering_drawing_register;
drop policy if exists "Portal users can update drawing register" on public.engineering_drawing_register;
create policy "Portal users can view drawing register" on public.engineering_drawing_register for select to authenticated using(public.has_module_access('engineering_drawing','view'));
create policy "Portal users can add drawing register" on public.engineering_drawing_register for insert to authenticated with check(public.has_module_access('engineering_drawing','add'));
create policy "Portal users can update drawing register" on public.engineering_drawing_register for update to authenticated using(public.has_module_access('engineering_drawing','edit')) with check(public.has_module_access('engineering_drawing','edit'));

-- WLS table + RLS
create table if not exists public.wls_reports (
 id bigint generated by default as identity primary key,
 sr_no integer, report_no text unique not null, customer_name text, unit_plant text,
 prepared_by text, reviewed_by text, approved_by text, short_name text, part_no text,
 part_type text, cavity_no text, tolerance_standard text, drawing_revision text,
 report_type text, report_revision text, alignment text, report_date date,
 stage_purpose text, conclusion text, abnormality text, remarks text,
 created_at timestamptz default now(), updated_at timestamptz default now()
);
alter table public.wls_reports enable row level security;
drop policy if exists "Authenticated users can view WLS reports" on public.wls_reports;
drop policy if exists "Authenticated users can add WLS reports" on public.wls_reports;
drop policy if exists "Authenticated users can update WLS reports" on public.wls_reports;
drop policy if exists "Portal users can view WLS reports" on public.wls_reports;
drop policy if exists "Portal users can add WLS reports" on public.wls_reports;
drop policy if exists "Portal users can update WLS reports" on public.wls_reports;
create policy "Portal users can view WLS reports" on public.wls_reports for select to authenticated using(public.has_module_access('wls','view'));
create policy "Portal users can add WLS reports" on public.wls_reports for insert to authenticated with check(public.has_module_access('wls','add'));
create policy "Portal users can update WLS reports" on public.wls_reports for update to authenticated using(public.has_module_access('wls','edit')) with check(public.has_module_access('wls','edit'));

-- Master Part List RLS
alter table public.master_part_list enable row level security;
drop policy if exists "Portal users can view master part list" on public.master_part_list;
drop policy if exists "Portal users can add master part list" on public.master_part_list;
drop policy if exists "Portal users can update master part list" on public.master_part_list;
create policy "Portal users can view master part list" on public.master_part_list for select to authenticated using(public.has_module_access('master_part','view'));
create policy "Portal users can add master part list" on public.master_part_list for insert to authenticated with check(public.has_module_access('master_part','add'));
create policy "Portal users can update master part list" on public.master_part_list for update to authenticated using(public.has_module_access('master_part','edit')) with check(public.has_module_access('master_part','edit'));

-- Permission table: Admin only
alter table public.user_module_permissions enable row level security;
drop policy if exists "Admins manage module permissions" on public.user_module_permissions;
drop policy if exists "Users view own module permissions" on public.user_module_permissions;
create policy "Admins manage module permissions" on public.user_module_permissions for all to authenticated using(public.is_portal_admin()) with check(public.is_portal_admin());
create policy "Users view own module permissions" on public.user_module_permissions for select to authenticated using(user_id=auth.uid());

-- Audit + WhatsApp queue
alter table public.portal_audit_log enable row level security;
drop policy if exists "Admins view audit log" on public.portal_audit_log;
drop policy if exists "Users view own audit log" on public.portal_audit_log;
create policy "Admins view audit log" on public.portal_audit_log for select to authenticated using(public.is_portal_admin());
create policy "Users view own audit log" on public.portal_audit_log for select to authenticated using(actor_id=auth.uid());

alter table public.whatsapp_notifications enable row level security;
drop policy if exists "Admins manage whatsapp notifications" on public.whatsapp_notifications;
create policy "Admins manage whatsapp notifications" on public.whatsapp_notifications for all to authenticated using(public.is_portal_admin()) with check(public.is_portal_admin());

create or replace function public.log_portal_change()
returns trigger language plpgsql security definer set search_path=public as $$
declare p jsonb; label text; actor_name text; actor_mobile text; actor_email text; rid text;
begin
 p:=case when TG_OP='DELETE' then to_jsonb(OLD) else to_jsonb(NEW) end;
 rid:=coalesce(p->>'id',p->>'register_no',p->>'report_no',p->>'part_no','?');
 label:=coalesce(p->>'drawing_no',p->>'report_no',p->>'part_no',p->>'register_no',rid);
 select employee_name,mobile_no,official_email into actor_name,actor_mobile,actor_email from public.user_profiles where id=auth.uid();
 insert into public.portal_audit_log(module,record_id,action,actor_id,actor_name,actor_mobile,actor_email,record_label,old_data,new_data)
 values(TG_ARGV[0],rid,TG_OP,auth.uid(),actor_name,actor_mobile,actor_email,label,
 case when TG_OP in('UPDATE','DELETE') then to_jsonb(OLD) else null end,
 case when TG_OP in('INSERT','UPDATE') then to_jsonb(NEW) else null end);
 return coalesce(NEW,OLD);
end; $$;

drop trigger if exists trg_audit_engineering_drawing on public.engineering_drawing_register;
create trigger trg_audit_engineering_drawing after insert or update or delete on public.engineering_drawing_register for each row execute function public.log_portal_change('engineering_drawing');
drop trigger if exists trg_audit_wls on public.wls_reports;
create trigger trg_audit_wls after insert or update or delete on public.wls_reports for each row execute function public.log_portal_change('wls');
drop trigger if exists trg_audit_master_part on public.master_part_list;
create trigger trg_audit_master_part after insert or update or delete on public.master_part_list for each row execute function public.log_portal_change('master_part');

create index if not exists idx_permissions_user on public.user_module_permissions(user_id);
create index if not exists idx_master_part_plant on public.master_part_list(plant_unit);
create index if not exists idx_master_part_part_no on public.master_part_list(part_no);
create index if not exists idx_audit_created on public.portal_audit_log(created_at);
create index if not exists idx_audit_module on public.portal_audit_log(module);
create index if not exists idx_whatsapp_recipient on public.whatsapp_notifications(recipient_user_id);
