-- Mutha Quality Portal: 3D Scanning DWM + 2 Shift OEE + Task Assignment
-- Run after PORTAL_ACCESS_MASTERPART_AUDIT.sql

ALTER TABLE public.user_module_permissions DROP CONSTRAINT IF EXISTS user_module_permissions_module_check;
ALTER TABLE public.user_module_permissions ADD CONSTRAINT user_module_permissions_module_check
CHECK (module IN ('engineering_drawing','wls','master_part','scanning_dwm'));

-- Expand existing master_part_list created by earlier portal versions.
ALTER TABLE public.master_part_list ADD COLUMN IF NOT EXISTS item_code_wls text;
ALTER TABLE public.master_part_list ADD COLUMN IF NOT EXISTS short_name text;
ALTER TABLE public.master_part_list ADD COLUMN IF NOT EXISTS drawing_revision text;
ALTER TABLE public.master_part_list ADD COLUMN IF NOT EXISTS customer_vendor text;
ALTER TABLE public.master_part_list ADD COLUMN IF NOT EXISTS moulding_process text;
ALTER TABLE public.master_part_list ADD COLUMN IF NOT EXISTS material_grade text;
ALTER TABLE public.master_part_list ADD COLUMN IF NOT EXISTS frequency text;
ALTER TABLE public.master_part_list ADD COLUMN IF NOT EXISTS active_status text;
ALTER TABLE public.master_part_list ADD COLUMN IF NOT EXISTS total_plan_qty numeric;
ALTER TABLE public.master_part_list ADD COLUMN IF NOT EXISTS low_plan numeric;
ALTER TABLE public.master_part_list ADD COLUMN IF NOT EXISTS medium_plan numeric;
ALTER TABLE public.master_part_list ADD COLUMN IF NOT EXISTS high_plan numeric;
ALTER TABLE public.master_part_list ADD COLUMN IF NOT EXISTS plan_months text;
ALTER TABLE public.master_part_list ADD COLUMN IF NOT EXISTS dispatch_type text;
ALTER TABLE public.master_part_list ADD COLUMN IF NOT EXISTS core_availability text;
ALTER TABLE public.master_part_list ADD COLUMN IF NOT EXISTS pattern_cavities numeric;
ALTER TABLE public.master_part_list ADD COLUMN IF NOT EXISTS plan_qty_cast numeric;
ALTER TABLE public.master_part_list ADD COLUMN IF NOT EXISTS core_boxes numeric;
ALTER TABLE public.master_part_list ADD COLUMN IF NOT EXISTS main_core_cavities numeric;
ALTER TABLE public.master_part_list ADD COLUMN IF NOT EXISTS side_core_cavities numeric;

CREATE TABLE IF NOT EXISTS public.scanning_engineers (
 id bigint generated by default as identity primary key,
 user_id uuid unique references auth.users(id) on delete cascade,
 engineer_name text not null,
 employee_id text,
 plant_unit text,
 default_shift text check (default_shift in ('A','B')),
 active boolean not null default true,
 created_at timestamptz default now(), updated_at timestamptz default now()
);

CREATE TABLE IF NOT EXISTS public.scanning_tasks (
 id bigint generated by default as identity primary key,
 task_no text unique,
 task_date date not null default current_date,
 shift_code text not null check (shift_code in ('A','B')),
 plant_unit text not null,
 assigned_engineer_id bigint references public.scanning_engineers(id) on delete set null,
 customer_name text,
 part_short_name text,
 part_no text,
 material_type text,
 cavity_note text,
 received_qty numeric,
 unit text,
 priority text default 'Medium',
 work_type text,
 work_details text,
 reason text,
 planned_minutes numeric default 0,
 actual_start timestamptz,
 actual_end timestamptz,
 actual_minutes numeric default 0,
 downtime_minutes numeric default 0,
 work_status text not null default 'Assigned',
 observation text,
 checker_status text,
 final_result text,
 completion_date date,
 report_no text,
 reports_sent_status text,
 remark text,
 assigned_by uuid references auth.users(id),
 created_by uuid references auth.users(id),
 updated_by uuid references auth.users(id),
 created_at timestamptz default now(), updated_at timestamptz default now()
);

CREATE TABLE IF NOT EXISTS public.scanning_downtime (
 id bigint generated by default as identity primary key,
 task_id bigint references public.scanning_tasks(id) on delete cascade,
 engineer_id bigint references public.scanning_engineers(id) on delete set null,
 downtime_date date not null default current_date,
 shift_code text not null check (shift_code in ('A','B')),
 plant_unit text not null,
 reason text not null,
 minutes numeric not null default 0,
 remarks text,
 created_by uuid references auth.users(id),
 created_at timestamptz default now()
);

CREATE INDEX IF NOT EXISTS idx_scan_task_date ON public.scanning_tasks(task_date);
CREATE INDEX IF NOT EXISTS idx_scan_task_engineer ON public.scanning_tasks(assigned_engineer_id);
CREATE INDEX IF NOT EXISTS idx_scan_task_shift ON public.scanning_tasks(shift_code);
CREATE INDEX IF NOT EXISTS idx_scan_task_plant ON public.scanning_tasks(plant_unit);
CREATE INDEX IF NOT EXISTS idx_scan_downtime_date ON public.scanning_downtime(downtime_date);

ALTER TABLE public.scanning_engineers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scanning_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scanning_downtime ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Scanning users can view engineers" ON public.scanning_engineers;
DROP POLICY IF EXISTS "Admins manage scanning engineers" ON public.scanning_engineers;
CREATE POLICY "Scanning users can view engineers" ON public.scanning_engineers FOR SELECT TO authenticated
USING (public.has_module_access('scanning_dwm','view'));
CREATE POLICY "Admins manage scanning engineers" ON public.scanning_engineers FOR ALL TO authenticated
USING (public.is_portal_admin()) WITH CHECK (public.is_portal_admin());

DROP POLICY IF EXISTS "Scanning users view tasks" ON public.scanning_tasks;
DROP POLICY IF EXISTS "Scanning users add tasks" ON public.scanning_tasks;
DROP POLICY IF EXISTS "Scanning users update tasks" ON public.scanning_tasks;
CREATE POLICY "Scanning users view tasks" ON public.scanning_tasks FOR SELECT TO authenticated
USING (public.has_module_access('scanning_dwm','view'));
CREATE POLICY "Scanning users add tasks" ON public.scanning_tasks FOR INSERT TO authenticated
WITH CHECK (public.has_module_access('scanning_dwm','add'));
CREATE POLICY "Scanning users update tasks" ON public.scanning_tasks FOR UPDATE TO authenticated
USING (public.has_module_access('scanning_dwm','edit')) WITH CHECK (public.has_module_access('scanning_dwm','edit'));

DROP POLICY IF EXISTS "Scanning users view downtime" ON public.scanning_downtime;
DROP POLICY IF EXISTS "Scanning users add downtime" ON public.scanning_downtime;
DROP POLICY IF EXISTS "Scanning users update downtime" ON public.scanning_downtime;
CREATE POLICY "Scanning users view downtime" ON public.scanning_downtime FOR SELECT TO authenticated
USING (public.has_module_access('scanning_dwm','view'));
CREATE POLICY "Scanning users add downtime" ON public.scanning_downtime FOR INSERT TO authenticated
WITH CHECK (public.has_module_access('scanning_dwm','add'));
CREATE POLICY "Scanning users update downtime" ON public.scanning_downtime FOR UPDATE TO authenticated
USING (public.has_module_access('scanning_dwm','edit')) WITH CHECK (public.has_module_access('scanning_dwm','edit'));

-- Historical 2025 register import table. Import the supplied CSV into this table.
CREATE TABLE IF NOT EXISTS public.scanning_register_history (
 id bigint generated by default as identity primary key,
 source_sr_no integer,
 task_date date,
 plant_unit text,
 part_short_name text,
 material_type text,
 cavity_note text,
 received_qty numeric,
 unit text,
 customer_name text,
 priority text,
 work_type text,
 work_details text,
 reason text,
 inspection_date date,
 work_status text,
 observation text,
 checker_status text,
 final_result text,
 completion_date date,
 reports_sent_status text,
 remark text,
 imported_at timestamptz default now()
);
ALTER TABLE public.scanning_register_history ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Scanning users view history" ON public.scanning_register_history;
DROP POLICY IF EXISTS "Admins manage history" ON public.scanning_register_history;
CREATE POLICY "Scanning users view history" ON public.scanning_register_history FOR SELECT TO authenticated
USING (public.has_module_access('scanning_dwm','view'));
CREATE POLICY "Admins manage history" ON public.scanning_register_history FOR ALL TO authenticated
USING (public.is_portal_admin()) WITH CHECK (public.is_portal_admin());

-- Daily OEE-style KPI for scanning work: Availability x Performance x Quality.
-- Planned minutes = task planned time. Availability accounts for recorded downtime.
-- Performance = planned minutes / actual minutes, capped at 100%.
-- Quality = OK/Approved tasks / completed tasks.
CREATE OR REPLACE VIEW public.scanning_oee_daily AS
SELECT
 t.task_date,
 t.plant_unit,
 t.shift_code,
 t.assigned_engineer_id,
 COUNT(*) AS total_tasks,
 COUNT(*) FILTER (WHERE lower(coalesce(t.work_status,''))='completed') AS completed_tasks,
 COALESCE(SUM(t.planned_minutes),0) AS planned_minutes,
 COALESCE(SUM(t.actual_minutes),0) AS actual_minutes,
 COALESCE(SUM(t.downtime_minutes),0) AS downtime_minutes,
 ROUND((CASE WHEN COALESCE(SUM(t.planned_minutes),0)>0
   THEN GREATEST(0, LEAST(1,(SUM(t.planned_minutes)-SUM(t.downtime_minutes))/SUM(t.planned_minutes))) ELSE 0 END)*100,2) AS availability_pct,
 ROUND((CASE WHEN COALESCE(SUM(t.actual_minutes),0)>0
   THEN GREATEST(0, LEAST(1,SUM(t.planned_minutes)/SUM(t.actual_minutes))) ELSE 0 END)*100,2) AS performance_pct,
 ROUND((CASE WHEN COUNT(*) FILTER (WHERE lower(coalesce(t.work_status,''))='completed')>0
   THEN COUNT(*) FILTER (WHERE lower(coalesce(t.work_status,''))='completed' AND upper(coalesce(t.final_result,'')) IN ('OK','APPROVED'))::numeric /
        COUNT(*) FILTER (WHERE lower(coalesce(t.work_status,''))='completed') ELSE 0 END)*100,2) AS quality_pct
FROM public.scanning_tasks t
GROUP BY t.task_date,t.plant_unit,t.shift_code,t.assigned_engineer_id;

COMMENT ON VIEW public.scanning_oee_daily IS 'OEE-style daily scanning KPI: Availability x Performance x Quality. Use for engineer/shift/plant dashboard.';
